version: '3.8'

services:
  dora:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./dora:/app/dora
    command: --city "New York" --output pretty
    # Override the command with your own arguments when running:
    # docker-compose run --rm dora --city "Paris" --output json